Release notes for Salesforce package 3.8
helpshift/helpshift-docs pull request #104
Opened 2023-09-22 04:12 UTC by rohit369-hs

Add release notes for salesforce package 3.8

2023-09-22 06:34 UTC, hs-saunved approved these changes

2023-09-25 04:48 UTC, hs-shantanu commented on docs/salesforce/release-notes.mdx
> +- Added fixes for clearing Salesforce security review, thus improving package security.
Do we need to mention Salesforce security review?
We can just say - Add fixes for improving package security.

2023-09-25 04:49 UTC, hs-shantanu requested changes
One minor change, otherwise LGTM.

2023-09-25 04:52 UTC, hs-shantanu approved these changes

2023-09-25 04:58 UTC, merged