Feature/hs 1881
helpshift/helpshift-docs pull request #131
Opened 2024-05-09 07:31 UTC by dv-Gogna

Some code blocks have extra spaces around the actual content.
so we have removed those extra spaces.

2024-05-10 04:23 UTC, hs-hritik commented on docs/android/tutorials.mdx
> +```xml
Replaace `xml` with `text`

2024-05-10 04:45 UTC, hs-hritik commented on docs/ios/delegates.mdx
> -
`}` is out of the code blocks, could add that inside the code blocks.

2024-05-10 04:50 UTC, hs-hritik requested changes
LGTM. Added some minor suggestion. Thanks for doing this.

2024-05-13 10:29 UTC, hs-saunved requested changes

2024-05-13 10:29 UTC, hs-saunved commented on docs/cocos2d-x/sdk-configuration-android.mdx
>  ```cppp
This should be `cpp`
Please check if there are other such instances where the code block value is incorrect.

2024-05-13 10:29 UTC, hs-saunved commented on docs/android/troubleshooting.mdx
> +```java
This is not Java.
Please make this `text`

2024-05-13 10:29 UTC, hs-saunved commented on docs/android/troubleshooting.mdx
> +```java
Same as above.

2024-05-13 10:29 UTC, hs-saunved commented on docs/android/troubleshooting.mdx
> +```java
Same as above

2024-05-13 10:29 UTC, hs-saunved commented on docs/android/troubleshooting.mdx
> +```java
Same as above

2024-05-13 10:29 UTC, hs-saunved commented on docs/android/troubleshooting.mdx
> +```java
Same as above

2024-05-13 10:29 UTC, hs-saunved commented on docs/pc-and-console/helpshift-apis.mdx
> +```json
Same as above

2024-05-13 10:29 UTC, hs-saunved commented on docs/web/helpshift-apis.mdx
> +```json
text

2024-05-14 18:37 UTC, hs-hritik approved these changes

2024-05-14 18:39 UTC, hs-hritik commented on docs/ios/delegates.mdx
> -
@dv-Gogna I think, this is not resolved.

2024-05-15 09:19 UTC, hs-saunved approved these changes

2024-05-16 06:18 UTC, merged