Update setLanguage API is deprecated.
helpshift/helpshift-docs pull request #132
Opened 2024-05-09 10:06 UTC by dv-Gogna

`setLanguage` API is deprecated. So updated the documentation.

2024-05-09 11:25 UTC, hs-saunved requested changes

2024-05-09 11:25 UTC, hs-saunved commented on docs/web-chat/internationalization.mdx
> +<Admonition type="danger" title="Note">
Change the title to "Deprecation notice" instead of "Note"

2024-05-09 11:25 UTC, hs-saunved commented on docs/web-chat/internationalization.mdx
> +The preferred way to set the language is to use the `helpshiftConfig` object. `setLanguage` API is deprecated.
The preferred way to set the language is to use the `helpshiftConfig` object because the`setLanguage` API is deprecated.

2024-05-10 04:55 UTC, hs-hritik approved these changes
LGTM

2024-05-13 10:31 UTC, hs-saunved commented on docs/web-chat/internationalization.mdx
> +Alternatively, you can call the `setLanguage` API (Deprecated) to set the language after the initialization code.
On Line 98, the comment says "set language to french", but the language key is being set to "de".
Please change it to "fr".

2024-05-13 10:33 UTC, hs-saunved requested changes

2024-05-13 10:33 UTC, hs-saunved commented on docs/web-chat/internationalization.mdx
>  };
After the `};` on the next line, please add this (in the same code block):

```js
// If you are setting language dynamically (i.e. after Web Chat has loaded),
// then refresh the widget:
Helpshift("updateHelpshiftConfig");
```

2024-05-15 09:20 UTC, hs-saunved approved these changes

2024-05-16 06:25 UTC, merged