Add PC Widget Docs
helpshift/helpshift-docs pull request #157
Opened 2024-12-24 05:48 UTC by saga-hs

2024-12-24 14:35 UTC, rohan-helpshift requested changes

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +title: List of Available APIs
Keep title to other SDK docs

"Helpshift APIs"

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +**Description:** Initializes the HelpShift widget and runs it in the background, enabling it to listen for notifications. If notifications are a high priority, this method should be called when the g
Should be before parameters.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +**Parameters:**
Use table

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +**Example Usage:**
specific language for snippet for formatting.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +- `Note:` Clicking the "X" button on the widget also triggers the hide functionality.
Why code formatting is here? Remove.

Also whole description could be better phrased.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +**Parameters:** None
None should be on new line.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +```
Specify language

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +### HelpShift.CleanUp
Line above

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +**Parameters:** None
None on new line.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +**Description:**
Move before params.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +Shuts down the Helpshift widget and terminates its background process. This method should be called during game shutdown to release resources and ensure proper cleanup.
Better phrase

Shuts down -> Destroy

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +- `Usage:` Call this inside Unity's `OnApplicationQuit()` method.
Remove code formatting.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +```
Specify language

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +### HelpShift.Update ( Optional )
No space needed between ( ) brackets.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +**Parameters:** None
None on new line.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +- `Note:` This is optional in the current workflow as no events are being sent from the widget to Unity.
Remove code formatting.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/available-apis.mdx
> +```
Specify language

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/build-project.mdx
> +---
Delete this file, this is internal process, not part of dev docs.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +### Properties:
Use table.

Required should be also part of the table, with true & false info. True -> config is required,

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +- `Default`: string.Empty
""

Not `string.Empty`

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +- `Default`: false
Instead of Default, `false` should be formatted as code.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +```
Specify language.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +    ////////////////////////////////////
Remove comment

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +Helpshift.Initialize(Application.streamingAssetsPath,config);
Space between params

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +### Mode Previews
Table

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/environment-setup.mdx
> +---
Remove this file. This is internal process, not part of dev docs.

2024-12-24 14:35 UTC, rohan-helpshift commented on docs/pc-widget-unity/integration.mdx
> +This approach is the standard approach, where the game developers will have control over the widget's life cycle using the set of API's that are provided.
Add line break here, right now text flow after image.

2025-01-03 05:26 UTC, hs-umang commented on docs/pc-widget-unity/available-apis.mdx
> +### HelpShift.CleanUp
Make Helpshift consistent everywhere

2025-01-03 05:26 UTC, hs-umang commented on docs/pc-widget-unity/available-apis.mdx
> +### HelpShift.CleanUp
Do we want to start API names with capital letters? Or should it be `Helpshift.show` instead of `Helpshift.Show

2025-01-03 05:26 UTC, hs-umang commented on docs/pc-widget-unity/available-apis.mdx
> +Handles events sent from the HelpShift widget to Unity. This method is typically called inside Unity's Update() method.
Do we want to mention Helpshift Widget in the docs because it is internal to us and the customers/developers does need to know about it?

2025-01-03 05:26 UTC, hs-umang commented on docs/pc-widget-unity/build-project.mdx
> +Configure the Publish option to produce the files in a local folder.
publish option & Use the below publish profile settings?

2025-01-03 05:26 UTC, hs-umang commented on docs/pc-widget-unity/configuration.mdx
> +### Properties:
+1

2025-01-03 05:26 UTC, hs-umang commented on docs/pc-widget-unity/configuration.mdx
> +    ////////////////////////////////////
Shouldn't the fields like Domain, PlatformId be in lowercase?

2025-01-03 05:26 UTC, hs-umang commented on docs/pc-widget-unity/integration.mdx
> +This approach is the standard approach, where the game developers will have control over the widget's life cycle using the set of API's that are provided.
refer the "Available APIs" section where you are saying - "using the set of API's that are provided" (if that is what is you are referring to here)

2025-01-06 10:01 UTC, saga-hs commented on docs/pc-widget-unity/available-apis.mdx
> +**Example Usage:**
It is not possible when we are using the <code> component

2025-01-06 10:02 UTC, saga-hs commented on docs/pc-widget-unity/available-apis.mdx
> +```
It is not possible when we are using the `<code>` component

2025-01-06 10:02 UTC, saga-hs commented on docs/pc-widget-unity/available-apis.mdx
> +### HelpShift.CleanUp
Helpshift made consistent

PC Widget C sharp API are like this Helpshift.Show

2025-01-06 10:03 UTC, saga-hs commented on docs/pc-widget-unity/available-apis.mdx
> +```
same as above

2025-01-06 10:05 UTC, saga-hs commented on docs/pc-widget-unity/available-apis.mdx
> +Handles events sent from the HelpShift widget to Unity. This method is typically called inside Unity's Update() method.
Yes, as we are using Helpshift web widget in PC widget

2025-01-06 10:09 UTC, saga-hs commented on docs/pc-widget-unity/build-project.mdx
> +Configure the Publish option to produce the files in a local folder.
Yes, but this is for internal use.

2025-01-06 10:10 UTC, saga-hs commented on docs/pc-widget-unity/configuration.mdx
> +    ////////////////////////////////////
It is because of the C sharp conventions

2025-01-08 11:27 UTC, hs-umang commented on docs/pc-widget-unity/build-project.mdx
> +Configure the Publish option to produce the files in a local folder.
I meant the lowercasing of the words 😅

2025-01-08 11:30 UTC, hs-umang commented on docs/pc-widget-unity/helpshift-apis.mdx
> +            Initializes the Helpshift widget and runs it in the background, enabling it to listen for notifications.<br/><br/>
Please change Helpshift widget -> Helpshift Widget everywhere

2025-01-08 11:30 UTC, hs-umang commented on docs/pc-widget-unity/helpshift-apis.mdx
> +            Initializes the Helpshift widget and runs it in the background, enabling it to listen for notifications.<br/><br/>
Also check with product if we want to have PC widget as PC Widget?

2025-01-13 10:38 UTC, rohan-helpshift requested changes

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +A configuration object has to be created, which should be passed to the `initialize` API.
Rephrase this line. Ref to Web Widget page.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +# Mandatory Configuration
Remove this heading.

This could be labelled as base config. All configs should be at same level.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +1. Replace `YOUR_DOMAIN` with your Helpshift domain.
Same description as point #2. Instead of giving text descriptions, use screenshot.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +3. Replace `YOUR_APP_ID` with details found at `Settings` > `Your App (eg. Helpshift Demo App)` > `Publish ID`.
`Settings` > `Your App (eg. Helpshift Demo App)` > `Publish ID`

This part is not code snipped, avoid code formatting. Use em or bold if needed.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +Above mentioned configuration like `Domain`, `PlatformId`, `AppId` are mandatory for initializing the Helpshift PC Widget. For additional configurations refer below.
This should be part of top level descriptions.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +# Optional Configuration
Remove

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +## Initial user message {#initial-user-message}
Description is missing.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +## Conversation prefill text {#conversation-prefill-text}
Description is missing.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +## Tags
Title name changed.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +## Tags
Filter param is not added? Check once.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +Determines how the widget resizes. Example values include `ResizeMode.SlimRight`, `ResizeMode.SlimCenter`, `ResizeMode.SlimLeft`, `ResizeMode.WideCenter`, and `ResizeMode.FullScreen`.
Rephrase. Widget does not resize, it take up space on first load as per given value.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +Determines how the widget resizes. Example values include `ResizeMode.SlimRight`, `ResizeMode.SlimCenter`, `ResizeMode.SlimLeft`, `ResizeMode.WideCenter`, and `ResizeMode.FullScreen`.
Add a note to refer below table for possible values, instead of repeating here.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/getting-started.mdx
> +  Follow these simple steps to add Helpshift in-game support to Unity game right away:
Remove colon (:) at end of line. Add full-stop instead.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/helpshift-apis.mdx
> +**Description:**
Remove colon. Also use h4 or h5, better spacing as headers.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/helpshift-apis.mdx
> +| `helpshiftConfig` | object | A configuration object for the widget.                                                  |
Type here should be customer right?

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/helpshift-apis.mdx
> +## Helpshift.Initialize
Initialize Helpshift Widget

similar format at other places.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/internationalization.mdx
> +In order to ensure a smooth migration for existing users, the default language is set to English (`en`) i.e. if you don't set the `Language` option in the `HelpshiftConfig` object, Helpshift PC Widge
This not is confusing. In the context of a web widget browser makes sense, but in PC widget it does not. We need to discuss if we even need to support this.

2025-01-13 10:38 UTC, rohan-helpshift commented on docs/pc-widget-unity/users.mdx
> +# Users {#users}
userAuthToken part is missing.

2025-01-16 04:51 UTC, saga-hs commented on docs/pc-widget-unity/helpshift-apis.mdx
> +            Initializes the Helpshift widget and runs it in the background, enabling it to listen for notifications.<br/><br/>
Going with Helpshift Pc Widget

2025-01-16 05:18 UTC, saga-hs commented on docs/pc-widget-unity/helpshift-apis.mdx
> +| `helpshiftConfig` | object | A configuration object for the widget.                                                  |
I added HelpshiftConfig as a type.

2025-01-20 04:45 UTC, saga-hs commented on docs/pc-widget-unity/users.mdx
> +# Users {#users}
It is missing in code as well

2025-01-20 04:45 UTC, saga-hs commented on docs/pc-widget-unity/internationalization.mdx
> +In order to ensure a smooth migration for existing users, the default language is set to English (`en`) i.e. if you don't set the `Language` option in the `HelpshiftConfig` object, Helpshift PC Widge
Removed it

2025-01-20 04:46 UTC, saga-hs commented on docs/pc-widget-unity/helpshift-apis.mdx
> +**Description:**
Done

2025-01-20 04:46 UTC, saga-hs commented on docs/pc-widget-unity/configuration.mdx
> +Above mentioned configuration like `Domain`, `PlatformId`, `AppId` are mandatory for initializing the Helpshift PC Widget. For additional configurations refer below.
Done

2025-01-20 04:46 UTC, saga-hs commented on docs/pc-widget-unity/configuration.mdx
> +3. Replace `YOUR_APP_ID` with details found at `Settings` > `Your App (eg. Helpshift Demo App)` > `Publish ID`.
Done

2025-01-20 04:46 UTC, saga-hs commented on docs/pc-widget-unity/configuration.mdx
> +1. Replace `YOUR_DOMAIN` with your Helpshift domain.
Done

2025-01-20 04:46 UTC, saga-hs commented on docs/pc-widget-unity/configuration.mdx
> +# Mandatory Configuration
Done

2025-01-20 04:46 UTC, saga-hs commented on docs/pc-widget-unity/configuration.mdx
> +A configuration object has to be created, which should be passed to the `initialize` API.
Done

2025-01-20 15:22 UTC, rohan-helpshift requested changes

2025-01-20 15:22 UTC, rohan-helpshift commented on src/data/homeSections.json
> +        "description": "Integrate Helpshift widget in the PC unity games",
unity -> Unity

2025-01-24 11:46 UTC, rohan-helpshift requested changes

2025-01-24 11:46 UTC, rohan-helpshift commented on docs/pc-widget-unity/configuration.mdx
> +The `WidgetType` config value controls whether both Helpcenter and Web Chat, only Helpcenter, or only Web Chat should be loaded in the Helpshift Widget.
Helpshift Widget should be Helpshift PC Widget.

2025-01-24 11:46 UTC, rohan-helpshift commented on docs/pc-widget-unity/getting-started.mdx
> +### Get the latest PC Widget Unity SDK zip {#getting-sdk}
Remove zip

2025-01-27 04:29 UTC, rohan-helpshift approved these changes

2025-01-27 05:54 UTC, hs-umang approved these changes

2025-01-27 05:57 UTC, saga-hs commented
Merging it with 2 approvers.

2025-01-27 05:57 UTC, merged