Add desc about initiateChatOnLoad config
helpshift/helpshift-docs pull request #49
Opened 2023-04-03 05:32 UTC by rehanHS

2023-04-06 08:04 UTC, hs-saunved requested changes

2023-04-06 08:04 UTC, hs-saunved commented on docs/web-chat/configuration.mdx
> +#### Example Embed Code
```suggestion
### Example Embed Code
```

2023-04-06 08:04 UTC, hs-saunved commented on docs/web-chat/configuration.mdx
> +To do the above mentioned action developer will have to set `initiateChatOnLoad` config in `window.helpshiftConfig` and then use the [updateHelpshiftConfig](https://developers.helpshift.com/web-chat/
```suggestion
To do the above mentioned action, the developer will have to set `initiateChatOnLoad` config in `window.helpshiftConfig` and then use the [updateHelpshiftConfig](https://developers.helpshift.com/web-chat/api/#update-helpshift-config) API to start the new chat when the previous issue is resolved.
```

2023-04-06 08:04 UTC, hs-saunved commented on docs/web-chat/configuration.mdx
> +To open the widget [open](https://developers.helpshift.com/web-chat/api/#open-widget) api can be used.
```suggestion
To open the widget [open](https://developers.helpshift.com/web-chat/api/#open-widget) API can be used.
```

2023-04-06 08:52 UTC, rehanHS commented on docs/web-chat/configuration.mdx
> +#### Example Embed Code
As discussed making it 5 hashes

2023-04-06 08:52 UTC, rehanHS commented on docs/web-chat/configuration.mdx
> +To do the above mentioned action developer will have to set `initiateChatOnLoad` config in `window.helpshiftConfig` and then use the [updateHelpshiftConfig](https://developers.helpshift.com/web-chat/
Ack

2023-04-06 08:52 UTC, rehanHS commented on docs/web-chat/configuration.mdx
> +To open the widget [open](https://developers.helpshift.com/web-chat/api/#open-widget) api can be used.
Ack

2023-04-07 10:00 UTC, helpshift-vishal approved these changes
Approved

2023-04-07 11:43 UTC, hs-hritik approved these changes

2023-04-07 11:54 UTC, merged