Add initiate chat and presentFullScreenOniPad config
helpshift/helpshift-docs pull request #63
Opened 2023-05-11 05:58 UTC by IamJoyson

2023-05-18 08:50 UTC, jaydeep-helpshift requested changes

2023-05-18 08:50 UTC, jaydeep-helpshift commented on docs/sdkx-unity/sdk-configuration-ios.mdx
> +| Supported by | <code>showConversation</code>          |
This applies to showFAQs as well.

2023-05-18 09:59 UTC, helpshift-tanuj submitted a review, later dismissed

2023-06-27 09:02 UTC, jaydeep-helpshift approved these changes

2023-06-27 10:26 UTC, sumeet-helpshift approved these changes

2023-06-27 10:27 UTC, merged